scrape_configs:
  - job_name: "nestjs"
    static_configs:
      - targets: ["host.docker.internal:5000"]
    metrics_path: "/api/metrics"
    scrape_interval: 15s

  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]

    static_configs:
      - targets:
          - https://google.com
          - https://github.com
          - http://localhost:3000 # Your Grafana for example

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
