name: Deploy to server via Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MY_SSH_KEY }}
      - name: Checkout repo (optional, if needed for ansible playbook or files)
        uses: actions/checkout@v4
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass
      - name: Run ansible playbook on remote server
        run: |
          ansible-playbook -i "$SERVER_IP," -u root --ssh-extra-args="-o StrictHostKeyChecking=no" ansible/deploy-nest.yaml
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
