name: Deploy to server via Ansible

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test -- --ci
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MY_SSH_KEY }}
      - name: Checkout repo (optional, if needed for ansible playbook or files)
        uses: actions/checkout@v4
      - name: Run Ansible playbook
        run: |
          echo $(pwd)
          ansible-playbook -i ansible/inventory.ini ansible/deploy-nest.yaml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
