name: Deploy to server via Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MY_SSH_KEY }}
      - name: Checkout repo (optional, if needed for ansible playbook or files)
        uses: actions/checkout@v4
      - name: Run ansible playbook on remote server
      - name: Run ansible playbook on remote server
        run: |
          ls -la project/ansible   # debug
          ansible-playbook -i project/ansible/inventory.ini project/ansible/deploy-nest.yaml
